language: python

sudo: false

python:
- '3.7'

os:
- linux

install:
  - pip install -U coveralls
  - pip install -U coverage
  - pip install -U pylint
  - pip install -r test_requirements.txt

# before_script: # configure a headless display to test plot generation
# - "export DISPLAY=:99.0"
# - "sh -e /etc/init.d/xvfb start"
# - sleep 1 # give xvfb some time to start

script:
- python -m coverage run --source . -m unittest discover --verbose
# - python -m coverage run --source . setup.py test

after_success:
  # - python -m pylint --load-plugins=pylint.extensions.mccabe --docstring-min-length 5 --no-docstring-rgx "^(test)?_|.*Tests$" --unsafe-load-any-extension y --output-format colorized  --reports y $(find . -name "*.py")
  - python -m coverage report --show-missing
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a75d423f7dff38862a1a
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

  email: false
